spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root  
  jpa:
    show-sql: false
    generate-ddl: false
product:
    defaultCategory: fashion
eureka:
    client:
        register-with-eureka: true
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka